# Site settings
title: Project Portfolio
author:
  name: Agnes Ho
  email: agnesho392@gmail.com
description: "Agnes Ho's portfolio page"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
